### PR TITLE
 Add Alphabet Rangoli

### PR DESCRIPTION
**Pull request by AbhiTom2000**

### CODE REVIEW

**Comment by atulnair** [comment]
@AbhiTom2000  do you want to merge it as a single pr?

**Comment by Mr-Skully** [comment]
@AbhiTom2000, you could do it as three separate PRs if you'd like.

**Comment by AbhiTom2000** [comment]
Yes I want to do it as 3 pr.
I didn't know about it
Sorry and thank you.
Can you tell me how can I undo it?

**Comment by Mr-Skully** [comment]
> Yes I want to do it as 3 pr. I didn't know about it Sorry and thank you. Can you tell me how can I undo it?  

You could just delete any 2 files (out of the 3) from your repository, and the changes would automatically reflect in this PR.
You could create two more branches and keep adding one of the remaining files in each branch, and create PRs from each branch.
So you'll have three branches on your repo, and PRs from each of them.

**Comment by AbhiTom2000** [comment]
Ok. Thanks for helping me out.

**Pull request closed without merging**
